name: README

on:
    workflow_dispatch:
    schedule:
        - cron: "0 8 * * 1,3,5"

jobs:
    update-readme:
        name: Update README
        runs-on: ubuntu-latest
        steps:
            - uses: ism0080/comicstrip-readme@v1.2
              with:
                  SHOW_XKCD: true
            - uses: Platane/snk/svg-only@v2
              with:
                  github_user_name: cardoso-thiago
                  outputs: dist/github-snake.svg